// LOGIN ACTIONS
export const EMAIL_CHANGED = 'EMAIL_CHANGED';
export const PASSWORD_CHANGED = 'PASSWORD_CHANGED';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAIL = 'LOGIN_USER_FAIL';
export const LOGIN_USER = 'LOGIN_USER';

// MEALS ACTIONS
export const SET_INGREDIENT_CURRENT_BUILD = 'SET_INGREDIENT_CURRENT_BUILD';
export const SET_SELECTED_CURRENT_BUILD = 'SET_SELECTED_CURRENT_BUILD';
export const SAVE_CURRENT_MEAL = 'SAVE_CURRENT_MEAL';
export const RESET_CURRENT_MEAL = 'RESET_CURRENT_MEAL';

// INGREDIENTS ACTIONS
export const SET_INGREDIENTS = 'SET_INGREDIENTS';

// SHOP ACTIONS
export const SAVE_SHOP_LIST = 'SAVE_SHOP_LIST';
